#if COMPILE_JSON
/*
 * Auto generated by XrmFramework 2.0
 * Do not edit directly this file
 */
const dimsif_accountDefinition = {
    LogicalName: "dimsif_account",
    SchemaName: "Account",
    CollectionName: "dimsif_accounts",
    LogicalCollectionName: "dimsif_accounts",
    PrimaryIdAttribute: "dimsif_accountid",
    PrimaryNameAttribute: "dimsif_name",
    Columns: {
        Adresseemail: "cr5d4_adresseemail",
        Datedenaissance: "cr5d4_datedenaissance",
        Prenom: "cr5d4_prenom",
        TelephoneFixe: "cr5d4_telephonefixe",
        TelephonePortable: "cr5d4_telephoneportable",
        Id: "dimsif_accountid",
        Name: "dimsif_name"
    }
};
#endif
