#if COMPILE_JSON
/*
 * Auto generated by XrmFramework 2.0
 * Do not edit directly this file
 */
const cr5d4_lotlogementDefinition = {
    LogicalName: "cr5d4_lotlogement",
    SchemaName: "Lotlogement",
    CollectionName: "cr5d4_lotlogements",
    LogicalCollectionName: "cr5d4_lotlogements",
    PrimaryIdAttribute: "cr5d4_lotlogementid",
    PrimaryNameAttribute: "cr5d4_id",
    Columns: {
        Id: "cr5d4_id",
        Id: "cr5d4_lotlogementid",
        NbProspect: "cr5d4_nbprospect",
        Numero: "cr5d4_numero",
        Programme: "cr5d4_programme",
        PrixEuros: "dimsif_prixeuros"
    }
};
#endif
