#if COMPILE_JSON
/*
 * Auto generated by XrmFramework 2.0
 * Do not edit directly this file
 */
const dimsif_monstreDefinition = {
    LogicalName: "dimsif_monstre",
    SchemaName: "Monstre",
    CollectionName: "dimsif_monstres",
    LogicalCollectionName: "dimsif_monstres",
    PrimaryIdAttribute: "dimsif_monstreid",
    PrimaryNameAttribute: "dimsif_nom",
    Columns: {
        Id: "dimsif_monstreid",
        Nom: "dimsif_nom"
    }
};
#endif
