#if COMPILE_JSON
/*
 * Auto generated by XrmFramework 2.0
 * Do not edit directly this file
 */
const globalEnumsDefinition = {
    LogicalName: "globalEnums",
    SchemaName: "OptionSets",
    CollectionName: "",
    LogicalCollectionName: "",
    PrimaryIdAttribute: "",
    PrimaryNameAttribute: "",
    Enums: {
        EtatDuComposant: {
            Publie: 0,
            NonPublie: 1,
            Supprime: 2,
            NonPublieSupprime: 3
        },
        SynapseLinkProfileEntityType: {
            Requested: 0
        },
        SynapseLinkScheduleType: {
            Snapshot: 0,
            Incrementalupdate: 1
        }
    }
};
#endif
